const MIN = 60 * 1000
const now = Date.now()

export const MOCK_DRIVERS = [
  // Ativos
  {
    id: 'DRV-001',
    name: 'Carlos Ferreira',
    vehicle: 'Honda Civic',
    plate: 'ABC-1D23',
    zone: 'Centro',
    sector: 'Setor 01',
    status: 'active',
    categoryKey: 'moderate',
    connectedAt: now - 134 * MIN,
    lastSeen: now - 15 * 1000,
    kmToday: 47.3,
  },
  {
    id: 'DRV-002',
    name: 'Ana Paula Souza',
    vehicle: 'Toyota Corolla',
    plate: 'EFG-5H78',
    zone: 'Pinheiros',
    sector: 'Setor 03',
    status: 'active',
    categoryKey: 'drizzle',
    connectedAt: now - 89 * MIN,
    lastSeen: now - 8 * 1000,
    kmToday: 31.7,
  },
  {
    id: 'DRV-003',
    name: 'Pedro Henrique Lima',
    vehicle: 'VW Gol',
    plate: 'IJK-9012',
    zone: 'Santana',
    sector: 'Setor 05',
    status: 'active',
    categoryKey: 'dry',
    connectedAt: now - 201 * MIN,
    lastSeen: now - 22 * 1000,
    kmToday: 82.1,
  },
  {
    id: 'DRV-004',
    name: 'Mariana Costa',
    vehicle: 'Chevrolet Onix',
    plate: 'MNO-3P45',
    zone: 'Tatuapé',
    sector: 'Setor 06',
    status: 'active',
    categoryKey: 'heavy',
    connectedAt: now - 45 * MIN,
    lastSeen: now - 5 * 1000,
    kmToday: 18.9,
  },
  {
    id: 'DRV-005',
    name: 'Rafael Oliveira',
    vehicle: 'Hyundai HB20',
    plate: 'QRS-6T78',
    zone: 'Mooca',
    sector: 'Setor 06',
    status: 'active',
    categoryKey: 'moderate',
    connectedAt: now - 167 * MIN,
    lastSeen: now - 31 * 1000,
    kmToday: 64.5,
  },
  {
    id: 'DRV-006',
    name: 'Juliana Pereira',
    vehicle: 'Volkswagen Polo',
    plate: 'UVW-0X23',
    zone: 'Vila Madalena',
    sector: 'Setor 02',
    status: 'active',
    categoryKey: 'dry',
    connectedAt: now - 312 * MIN,
    lastSeen: now - 18 * 1000,
    kmToday: 118.3,
  },
  {
    id: 'DRV-007',
    name: 'Lucas Santana',
    vehicle: 'Ford Ka',
    plate: 'YZA-4B56',
    zone: 'Morumbi',
    sector: 'Setor 07',
    status: 'active',
    categoryKey: 'drizzle',
    connectedAt: now - 78 * MIN,
    lastSeen: now - 42 * 1000,
    kmToday: 29.8,
  },
  {
    id: 'DRV-008',
    name: 'Fernanda Rocha',
    vehicle: 'Fiat Uno',
    plate: 'CDE-8F90',
    zone: 'Lapa',
    sector: 'Setor 02',
    status: 'active',
    categoryKey: 'dry',
    connectedAt: now - 256 * MIN,
    lastSeen: now - 11 * 1000,
    kmToday: 94.7,
  },
  {
    id: 'DRV-009',
    name: 'Bruno Castro',
    vehicle: 'Toyota Yaris',
    plate: 'GHI-2J34',
    zone: 'Brooklin',
    sector: 'Setor 07',
    status: 'active',
    categoryKey: 'moderate',
    connectedAt: now - 34 * MIN,
    lastSeen: now - 6 * 1000,
    kmToday: 12.4,
  },
  // Inativos
  {
    id: 'DRV-010',
    name: 'Thiago Mendes',
    vehicle: 'Chevrolet Celta',
    plate: 'KLM-6N78',
    zone: 'Penha',
    sector: 'Setor 08',
    status: 'inactive',
    categoryKey: null,
    connectedAt: null,
    lastSeen: now - 85 * MIN,
    kmToday: 0,
  },
  {
    id: 'DRV-011',
    name: 'Camila Torres',
    vehicle: 'Honda Fit',
    plate: 'OPQ-0R23',
    zone: 'Mooca',
    sector: 'Setor 06',
    status: 'inactive',
    categoryKey: null,
    connectedAt: null,
    lastSeen: now - 142 * MIN,
    kmToday: 0,
  },
  {
    id: 'DRV-012',
    name: 'Diego Ramos',
    vehicle: 'VW Saveiro',
    plate: 'STU-4V56',
    zone: 'Campo Belo',
    sector: 'Setor 07',
    status: 'inactive',
    categoryKey: null,
    connectedAt: null,
    lastSeen: now - 268 * MIN,
    kmToday: 0,
  },
  {
    id: 'DRV-013',
    name: 'Amanda Silva',
    vehicle: 'Nissan Versa',
    plate: 'WXY-8Z01',
    zone: 'Lapa',
    sector: 'Setor 02',
    status: 'inactive',
    categoryKey: null,
    connectedAt: null,
    lastSeen: now - 47 * MIN,
    kmToday: 0,
  },
  {
    id: 'DRV-014',
    name: 'Rodrigo Melo',
    vehicle: 'Renault Sandero',
    plate: 'BCD-2E34',
    zone: 'Ipiranga',
    sector: 'Setor 06',
    status: 'inactive',
    categoryKey: null,
    connectedAt: null,
    lastSeen: now - 391 * MIN,
    kmToday: 0,
  },
]
